activos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('sistema.urls'), name='sistema'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistema/urls.py
from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView
from . import views


app_name = 'sistema'
urlpatterns = [     
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('computer/', TemplateView.as_view(template_name='computer.html'), name='computer'),
    path('repuestos/', TemplateView.as_view(template_name='repuestos.html'), name='repuestos'),
    path('accesorios/', TemplateView.as_view(template_name='accesorios.html'), name='accesorios'),
    path('informes/', TemplateView.as_view(template_name='informes.html'), name='informes'),
    path('admin/', admin.site.urls),
    path("activos", views.computer, name="computer"),
    path('crear/', views.crear_activo, name='crear_activo'),

    ]

sistema/models.py
from django.db import models

# Create your models here.
class Tipo_activo(models.Model):
    id=models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
        
class Ubicacion(models.Model):
    id=models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre
            
class Estado(models.Model):
    id=models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)

    def __str__(self):
         return self.nombre
            
class Empleado(models.Model):
    id=models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    cargo = models.CharField(max_length=100)
    area= models.CharField(max_length=100)
    email = models.EmailField()
    telefono = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
class Activos(models.Model):
    id=models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    marca = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    fecha_adquisicion = models.DateField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    Tipo_activo = models.ForeignKey('Tipo_activo', on_delete=models.CASCADE)
    Ubicacion = models.ForeignKey('Ubicacion', on_delete=models.CASCADE)
    Estado = models.ForeignKey('Estado', on_delete=models.CASCADE)
    Empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

sistema/forms.py
from django import forms
from .models import Activos

class ActivoForm(forms.ModelForm):
    class Meta:
        model = Activos
        fields = ['nombre', 'marca', 'modelo', 'fecha_adquisicion', 'valor', 
                  'Tipo_activo', 'Ubicacion', 'Estado', 'Empleado']

sistema/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from sistema.models import Activos
from .forms import ActivoForm


# Create your views here.

def computer(request):
    activos = Activos.objects.all()
    return render(request, "computer.html", {"activos": activos})


def crear_activo(request):
    if request.method == 'POST':
        form = ActivoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('computer')  # vuelve a la lista
    else:
        form = ActivoForm()
    return render(request, 'crear_activo.html', {'form': form})

sistema/templates/accesorios.html
{% extends 'base1.html' %} {% block container%}
    
         <h1>Accesorios</h1>
            <p>En esta pagina podremos visualizar todos los accesorios</p>
     
{% endblock %}

sistema/templates/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
        {% block title %}
            Sistema  Gestión de Activos
        {% endblock %}
    </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    </head>
    <body>
        <header>
            <div class="left">
                <div class="menu-container">
                    <div class="menu" id="menu">
                        <div></div>
                        <div></div>
                        <div></div>    
                    </div>
                </div>
                <div class="brand">
                    <img src="{% static 'icons/logo1.svg' %}" alt="icon-logo" class="logo" />
                    <span class="name">Fecadi</span>
                </div>
            </div>
            <div class="right">
                <a href="#" class="icons-header">
                    <img src="{% static 'icons/chat.svg' %}" alt="chat"/>
                </a>
                <a href="#" class="icons-header">
                    <img src="{% static 'icons/question.svg' %}" alt="question"/>
                </a>
                <a href="#" class="icons-header">
                    <img src="{% static 'icons/notification.svg' %}" alt="notification"/>
                </a>
                <img src="{% static 'icons/user.svg' %}" alt="img-user" class="user"/>
            </div> 
        </header>
        <div class="sidebar " id="sidebar">
                <nav>
                    <ul>
                        <li>
                            <a href="#" class="search" title="Buscar">
                                <img src="{% static 'icons/search1.svg' %}" alt="" />
                                <span>Buscar</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'sistema:index' %}" class= "selected" title="Pagina de Inicio">
                                <img src="{% static 'icons/dashboard.svg' %}" alt="" />
                                <span>Pagina de Inicio</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'sistema:computer' %}" title="Computadores">
                                <img src="{% static 'icons/pc.svg' %}" alt="" />
                                <span>Computadores</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" title="Repuestos">
                                <img src="{% static 'icons/repuesto.svg' %}" alt="" />
                                <span>Repuestos</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" title="Accesorios">
                                <img src="{% static 'icons/accesories.svg' %}" alt="" />
                                <span>Accesorios</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" title="Informes">
                                <img src="{% static 'icons/informe.svg' %}" alt="" />
                                <span>Informes</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" title="Compras">
                                <img src="{% static 'icons/compras.svg' %}" alt="" />
                                <span>Compras</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" title="Herramientas">
                                <img src="{% static 'icons/tool.svg' %}" alt="" />
                                <span>Herramientas</span>
                            </a>
                        </li>
                    </ul>            
                </nav>
        </div>
        <main id="main">
            {% block container %}
            {% endblock %}
        </main> 

        
            <footer>
                 © 2025 DFUSEDAD. Todos los derechos reservados.
            </footer>
        
            
        <script src="{% static 'js/script.js' %}"></script>   
    </body>
</html>

sistema/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema  Gestión de Activos</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>


</head>
<body>
    <div class="dark-mode-btn" id="dark-mode-btn">
        <i class='bx bx-moon'></i>
        <i class='bx bx-sun'></i>
    </div>
    <div class="sidebar" id="sidebar">
        <div class="header">
            <div class="menu-btn" id="menu-btn">
                <i class='bx bx-chevron-left'></i>
            </div>
            <div class="brand">
                <img class="brand-light" src="{% static 'icons/brand-light.svg' %}" alt="">
                <img class="brand-dark" src="{% static 'icons/brand-dark.svg' %}" alt="">
                <span>Fecadi</span>
            </div>
        </div>
            <div class="menu-container">
                <div class="search">
                    <i class='bx bx-search'></i>
                    <input type="search" placeholder="Buscar">
                </div>
                <ul class="menu">
                    <li class="menu-item menu-item-static active">
                        <a href="{% url 'sistema:index' %}"  class="menu-link">
                            <i class='bx bx-home-alt-2'></i>
                            <span>Inicio</span>
                        </a>
                    </li>
                    <li class="menu-item menu-item-dropdown">
                        <a href="#" class="menu-link">
                            <i class='bx  bx-desktop'  ></i>  
                            <span>Computadores</span>
                            <i class='bx bx-chevron-down'></i>
                        </a>
                    <ul class="sub-menu">
                        <li><a href="{% url 'sistema:computer' %}" class="sub-menu-link">Todos</a></li>
                        <li><a href="#" class="sub-menu-link">Asignados</a></li>
                        <li><a href="#" class="sub-menu-link">Solicitados</a></li>
                        <li><a href="#" class="sub-menu-link">De Baja</a></li>
                    </ul>
                    </li>
                    <li class="menu-item menu-item-static">
                        <a href="{% url 'sistema:repuestos' %}" class="menu-link">
                            <i class='bx  bx-chip'  ></i>  
                            <span>Repuestos</span>
                        </a>
                    </li>
                    <li class="menu-item menu-item-static">
                        <a href="{% url 'sistema:accesorios' %}" class="menu-link">
                            <i class='bx  bx-save'  ></i>   
                            <span>Accesorios</span>
                        </a>
                    </li>
                    <li class="menu-item menu-item-dropdown">
                        <a href="{% url 'sistema:informes' %}" class="menu-link">
                            <i class='bx bx-file-blank' ></i>
                            <span>Informes</span>
                        </a>
                    </li>
                </ul>       
            </div>
            <div class="footer">
                <ul class="menu">
                    <li class="menu-item menu-item-static">
                        <a href="#" class="menu-link">
                            <i class='bx bx-bell'></i>
                            <span>Notifications</span>
                        </a>
                    </li>
                    <li class="menu-item menu-item-static">
                        <a href="#" class="menu-link">
                            <i class='bx bx-cog'></i>
                            <span>Settings</span>
                        </a>
                    </li>
                </ul>
                <div class="user">
                    <div class="user-img">
                        <img src="{% static 'icons/logo1.svg' %}" alt="user">
                    </div>
                    <div class="user-data">
                        <span class="name">Diego Useda</span>
                        <span class="email">dfusedad@gmail.com</span>
                    </div>
                    <div class="user-icon">
                        <i class='bx bx-exit'></i>
                    </div>
                </div>
            </div>
    </div>
    <main>
        {% block container %}
        {% endblock %}
    </main>
     <script src="{% static 'js/script1.js' %}"></script> 
  </body>
</html>

sistema/templates/computer.html
{% extends 'base1.html' %}
{% block container %}

<div class="container">
    <!-- Encabezado con total de dispositivos -->
    <div class="header">
        <h2>Equipos de Computo</h2>
        <div class="badge">
            Total de dispositivos: {{ activos|length }}
        </div>
        <a href="{% url 'sistema:crear_activo' %}" class="btn btn-success">➕ Agregar nuevo</a>
    </div>

    <!-- Tabla de activos -->
    <div class="card">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Marca</th>
                    <th>Modelo</th>
                    <th>Fecha de Adquisición</th>
                    <th>Valor</th>
                    <th>Tipo</th>
                    <th>Ubicación</th>
                    <th>Estado</th>
                    <th>Empleado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for activo in activos %}
                <tr>
                    <td>{{ activo.id }}</td>
                    <td>{{ activo.nombre }}</td>
                    <td>{{ activo.marca }}</td>
                    <td>{{ activo.modelo }}</td>
                    <td>{{ activo.fecha_adquisicion }}</td>
                    <td>${{ activo.valor|floatformat:2 }}</td>
                    <td>{{ activo.Tipo_activo }}</td>
                    <td>{{ activo.Ubicacion }}</td>
                    <td>
                        <span class="estado 
                            {% if activo.Estado == 'Activo' %} verde 
                            {% elif activo.Estado == 'En reparación' %} amarillo 
                            {% else %} gris {% endif %}">
                            {{ activo.Estado }}
                        </span>
                    </td>
                    <td>{{ activo.Empleado }}</td>
                    <td>
                        <a href="" class="btn btn-edit">✏️ Editar</a>
                        <a href="" class="btn btn-delete" onclick="return confirm('¿Seguro que deseas eliminar este activo?');">🗑️ Eliminar</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="11" class="no-data">No hay activos registrados.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>



{% endblock %}


 

sistema/templates/crear_activo.html
{% extends 'base1.html' %}
{% block container %}

<div class="container">
    <h2>➕ Agregar Nuevo Activo</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-success">💾 Guardar</button>
        <a href="{% url 'sistema:computer' %}" class="btn btn-delete">❌ Cancelar</a>
    </form>
</div>

{% endblock %}

sistema/templates/index.html
{% extends 'base1.html' %} {% block container%}
{%load static%}
    
         <h1>Bienvenido al Sistema de Gestión de Activos</h1>  
         <p>Este es un sistema para gestionar los activos de la empresa.</p>
           

            
     
{% endblock %}        

sistema/templates/informes.html
{% extends 'base1.html' %} {% block container%}
    
         <h1>Informes</h1>
            <p>En esta pagina podremos visualizar todos los informes</p>
     
{% endblock %}

sistema/templates/repuestos.html
{% extends 'base1.html' %} {% block container%}
    
         <h1>Repuestos</h1>
            <p>En esta pagina podremos visualizar todos los repuestos</p>

{% endblock %} 